### ISSUE TITLE
Final Fantasy XIII texture issues.

### ISSUE THREAD

**Issue by torbol** [Joshua-Ashton/d9vk#103]
On linux, running under proton, shadows resolution 4096 x 4096 and 8192 x 8192 makes game don't work and hairs have texture problem:

![3tV0Fen](https://user-images.githubusercontent.com/45130968/57589022-04b5c200-751e-11e9-9505-6401e7c4c739.jpg)
![Captura de pantalla de 2019-05-07 12-13-47](https://user-images.githubusercontent.com/45130968/57589041-65dd9580-751e-11e9-88c6-d8359faf0b00.png)

I have read this error is due to msaa rendering, but i don't know what really means.

Im using Steam native client with:

Proton:4.2-3
Distro:Ubuntu 18.04.2 LTS
Kernel:5.1.0-050100-generic
RAM:16 GB
GPU Driver:4.5 Mesa 19.0.1 - padoka PPA
GPU:Radeon RX 590
CPU:AMD Ryzen 5 2600X Six-Core

**Comment by Joshua-Ashton** [comment]
Are you actually using D9VK? Proton does not come with D9VK out of the box.

A log would be appreciated.

**Comment by GitArUs** [comment]
Both things are rather game bugs and I doubt they can be worked around under Linux. These things are also happening on Windows. For Nvidia cards You have to use third-party configuration tool to fix broken hair transparency (Nvidia Inspector) - read about it here: https://forums.guru3d.com/threads/nvidia-anti-aliasing-guide-updated.357956/page-123.
As for shadow resolution I always sticked to lowest values. The game was crashing too much with anything higher than 512x512.
I haven't tried to play it with d9vk yet, I think I should give it a try.

**Comment by torbol** [comment]
I've tried to install d9vk in proton's prefix and now game don't launch (even when I change resolution and msaa). Anyone knows how to get .log file with proton?

**Comment by logan001** [comment]
set launch option with PROTON_LOG=1 %command% and you'll get a steam-apid.log in home folder.
but that will be proton logs. i don't know if it will show d9vk output. probably is better to do DXVK_LOG_LEVEL=none|error|warn|info|debug (pick one).

**Comment by Joshua-Ashton** [comment]
`I haven't tried to play it with d9vk yet, I think I should give it a try.` Then why report an issue here?

**Comment by torbol** [comment]
Thank you logan001, I have got proton log (attached in this message) when game launch crash, but I'm not able to obtain d9vk log.
[steam-292120.log](https://github.com/Joshua-Ashton/d9vk/files/3174042/steam-292120.log)

**Comment by aqxa1** [comment]
Since you have an AMD card, you could also try [Gallium Nine](https://github.com/iXit/wine-nine-standalone), which is a more mature project at the moment.

Regarding the D9VK logs, they should be in the game's directory, somewhere in <steam library location>/common/<game dir>.

**Comment by GitArUs** [comment]
wine-staging 4.7. This game works with D9VK, when d3d9.evictManagedOnUnlock = True in dxvk.conf, even with shadow resolution set to 8192x8192 (dxvk.conf must be in directory where ffxiiiimg_d3d9.log is found, not in the directory where ffxiiiimg.exe resides). 
[ffxiiiimg_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3193192/ffxiiiimg_d3d9.log)

When this setting is False (default), it reaches menu, but then crashes always because of memory allocation issues.
[ffxiiiimg_d3d9_fail.log](https://github.com/Joshua-Ashton/d9vk/files/3193242/ffxiiiimg_d3d9_fail.log)

The hair and eyelashes problem is still present though. Probably impossible to fix...

All above applies to FFXIII-2 as well.
[ffxiii2img_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3193193/ffxiii2img_d3d9.log)

As a side note - to have all three parts of the game here - Lightning Returns starts and reaches menu, but crashes when trying to enter the load screen or to start a new game:
00ef:fixme:d3dx:D3DXLoadSurfaceFromMemory Unhandled filter 0x80004.
[LRFF13_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3193209/LRFF13_d3d9.log)

Not a D9VK problem ?

**Comment by GitArUs** [comment]
I was wrong. It seems to be fixed by implementing alpha to coverage.

Before commit 5815a56a
![hairbefore](https://user-images.githubusercontent.com/12022598/58199848-ec356c80-7cc0-11e9-8dbf-b4509bbc6c5d.jpg)
After commit 5815a56a
![hairafter](https://user-images.githubusercontent.com/12022598/58199866-f9525b80-7cc0-11e9-9f92-f8a2dc9c7a1c.jpg)

Thank You.
(strange thing is Vanille did not change at all)

**Comment by torbol** [comment]
> I was wrong. It seems to be fixed by implementing alpha to coverage.
> 
> Before commit [5815a56](https://github.com/Joshua-Ashton/d9vk/commit/5815a56a6cb946b0ffd96083756a03a615dc91c6)
> ![hairbefore](https://user-images.githubusercontent.com/12022598/58199848-ec356c80-7cc0-11e9-8dbf-b4509bbc6c5d.jpg)
> After commit [5815a56](https://github.com/Joshua-Ashton/d9vk/commit/5815a56a6cb946b0ffd96083756a03a615dc91c6)
> ![hairafter](https://user-images.githubusercontent.com/12022598/58199866-f9525b80-7cc0-11e9-9f92-f8a2dc9c7a1c.jpg)
> 
> Thank You.
> (strange thing is Vanille did not change at all)

Hello, how can I implement alpha coverage? Sorry but I'm newbie in this world

**Comment by Joshua-Ashton** [comment]
I implemented alpha to coverage myself which is what he was talking about.

**Comment by torbol** [comment]
Ok and how can I turn on that function, what must I do?

**Comment by Joshua-Ashton** [comment]
Nothing. It's included in the latest builds.

**Comment by torbol** [comment]
Waaaaau this is another thing, thank you so so much guys for help and fix, now I can play it with max resolution (8192 x 8192 it's a little bit slowly, maybe it was my graphic card, but at least it runs well) and msaa 16.
![Captura de pantalla de 2019-05-24 00-05-51](https://user-images.githubusercontent.com/45130968/58289839-eff7ea80-7db7-11e9-98bb-51e05c01fc4e.png)
.
![Captura de pantalla de 2019-05-24 00-01-23](https://user-images.githubusercontent.com/45130968/58289596-3731ab80-7db7-11e9-9e58-7e619560f777.png)

**Comment by Joshua-Ashton** [comment]
8192 x 8192 shadow res + 16 msaa is gonna struggle on any system :P

**Comment by torbol** [comment]
Some keys doesn't appear when using d9vk

Without d9vk:
![Captura de pantalla de 2019-06-01 16-24-39](https://user-images.githubusercontent.com/45130968/58749747-0c67e700-848a-11e9-9948-42be1dce8cef.png)

Using d9vk:
![Captura de pantalla de 2019-06-01 16-24-54](https://user-images.githubusercontent.com/45130968/58749753-1558b880-848a-11e9-9d73-287a8e02c3ea.png)


Proton log:
[steam-292120.log](https://github.com/Joshua-Ashton/d9vk/files/3243842/steam-292120.log)

D9VK log:
[ffxiiiimg_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3243861/ffxiiiimg_d3d9.log)
