### ISSUE TITLE
[Question] Building in Linux

### ISSUE THREAD

**Issue by STiAT** [Joshua-Ashton/d9vk#130]
I've been trying to build d9vk in Linux (to be exact, Solus Linux).

I keep getting crashes after the finalized build with in example 0.11 built by me, and 0.11 prebuilt. I'd like to know why, or what's going wrong.

The first difference is, I'm getting .dll.so files as output, no .dlls. Renaming the .sos to .dll crashes d9vk with games where d9vk prebuilt works.

I'm using my systems wine, and I'm using that one to build too, that said, I use lutris to load the d9vk libs (because it's easier).

d9vk_build.sh.txt is my build script, d9vk_compile.txt the compile output and d9vk_crash.txt the crash report.

[build_d9vk.sh.txt](https://github.com/Joshua-Ashton/d9vk/files/3219856/build_d9vk.sh.txt)
[d9vk_build.txt](https://github.com/Joshua-Ashton/d9vk/files/3219857/d9vk_build.txt)
[d9vk_crash.txt](https://github.com/Joshua-Ashton/d9vk/files/3219858/d9vk_crash.txt)

Any ideas?

**Comment by ZachBacon** [comment]
so the dll.so extension is because you're building it as a wine lib, if you want the dll files, you need to build with the mingw compiler, which solus doesn't have, if you want to build using that, you can either use mxe.cc to compile your own mingw compiler to compile your own or my suggestion is to use a nightly

https://git.froggi.es/joshua/d9vk/-/jobs just click the cloud icon with the arrow pointing down and then you can load it that way.

**Comment by pchome** [comment]
>  I use lutris to load the d9vk libs (because it's easier)

Check this
`wget 'https://git.froggi.es/joshua/d9vk/-/jobs/artifacts/master/download?job=d9vk&scope=finished' -O d9vk.master.latest.zip`

**Comment by Joshua-Ashton** [comment]
Use MinGW builds... I don't support winelib builds, that's more of a @pchome thing :frog:
