### ISSUE TITLE
Please add correct manual about apitracing for D9VK

### ISSUE THREAD

**Issue by axredneck** [Joshua-Ashton/d9vk#152]
These instructions from bug report template are incorrect:

> **Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

Related issue: #48

**Comment by Joshua-Ashton** [comment]
This makes an issue if I want to merge back into DXVK at somepoint.

**Comment by axredneck** [comment]
@Joshua-Ashton maybe you just add link to https://tracehub.froggi.es/ temporarily and remove it later when merging with DXVK? I see users trying to apitrace unsuccessfully.

**Comment by pchome** [comment]
@axredneck 
AFAIK
1. template was created before the wrapper `d3d11.dll` was patched/published
  [dxvk/wiki/Common-issues#apitrace](https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace)
    > If you're opening an issue and you're having issues with making an apitrace, put these DLLs into the directory where yourgame.exe is located. This will create a file yourgame.trace without requiring further interaction.
2. recent `apitrace` release include those patches, but description is hard to find in wiki
    [apitrace/wiki/Steam#windows](https://github.com/apitrace/apitrace/wiki/Steam#windows)
    > To avoid issues with Steam or the own launchers, the most reliable way to trace is to manually to copy the pertinent `lib\wrappers` DLL(s) on the same folder as the game main executable:
    > 
    > * Copy d3d9.dll for D3D9 games
    > * Copy dxgitrace.dll, dxgi.dll and d3d11.dll for D3D11 games.
3. worth to look at "daily builds", since they may include [bug fixes](https://github.com/apitrace/apitrace/compare/8.0...master)
  https://people.freedesktop.org/~jrfonseca/apitrace/
    > These binaries are compiled and uploaded daily from master branch.

So, maybe worth to PR corrected template upstream (DXVK), then D9VK will automatically receive this update.

**Comment by Bfgeshka** [comment]
Maybe create wiki pages with details here? It wouldn't collide or merging, so you can write whatever.
