### ISSUE TITLE
Nostale Black Screen (Login)

### ISSUE THREAD

**Issue by jona-1993** [Joshua-Ashton/d9vk#186]
Black screen with the login screen.

![NostaleCapture](https://user-images.githubusercontent.com/32371525/60402144-e36f6a80-9b8b-11e9-8050-91d7982234ee.png)

### Software information
Nostale - Directx 9 enabled

### System information
- GPU: Nvidia geforce GTX 1050 ti
- Driver: 430.26
- Wine version: wine devel 4.11
- DXVK version: d3d9-fixed-function 078ae826

### Apitrace
Generated with Windows 10 (wine doesn't create file trace..)

[nostale.zip](https://github.com/Joshua-Ashton/d9vk/files/3344786/nostale.zip)

### Log files
- d3d9.log: 
[NostaleClientX_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3343323/NostaleClientX_d3d9.log)

**Comment by K0bin** [comment]
If you want it fixed, we'll need an apitrace.

**Comment by jona-1993** [comment]
An idea why i don't can create the apitrace?

command:
wine ./apitrace.exe trace --output ./nostale.trace -a d3d9 "/mnt/B656F38D56F34C9D/Program Shared/Nostale_FR/NostaleClientX.exe" EntwellNostaleClient

The file isn't generated.

**Comment by jona-1993** [comment]
I updated my Nvidia driver: 418.52.17

If it's easier for you, I created a log file with the login screen + the game. (It wasn't easy with the black screen ^^')

The game has a grey screen:

![NostaleGameCapture](https://user-images.githubusercontent.com/32371525/61548550-3d0ddb00-aa4e-11e9-838d-36810836bb1d.png)

I tested with 7dc01c53 build.

Last D9VK log:
[NostaleClientX_d3d9_19-07-19.log](https://github.com/Joshua-Ashton/d9vk/files/3411800/NostaleClientX_d3d9_19-07-19.log)

Last apitrace (it's a big file now..):
https://1drv.ms/u/s!Armc-fXVwasXg4VmdJDflP_6qv523w?e=pV0wO9

**Comment by jona-1993** [comment]
Api trace for the c768ad02 build.

https://1drv.ms/u/s!Armc-fXVwasXg491xG5kiO-jz1QFiQ?e=FC49Jv

**Comment by Joshua-Ashton** [comment]
Is this still a bug? Replaying your trace with the associated config works fine for me.

**Comment by jona-1993** [comment]
Yes, there are some bugs.

It's not visible with apitrace. Maybe a translation bug?

- GameShop bug

With d3d9 (Windows 10)

![Nostale-D3D9-Gameshop](https://user-images.githubusercontent.com/32371525/65813736-747cce80-e1d9-11e9-81fc-bb201b9189c9.png)

With d9vk (Linux) // I took a picture with my phone because I had some display problems with Linux screenshots 

![Nostale-D9VK-Gameshop](https://user-images.githubusercontent.com/32371525/65813787-ddfcdd00-e1d9-11e9-99e3-828ab9ac4046.jpg)

- Display Bugs

With d3d9

![Nostale-D3D9-MiniLand](https://user-images.githubusercontent.com/32371525/65813799-071d6d80-e1da-11e9-9eba-8b23770e42fe.jpg)

With d9vk // with annotations

![Nostale-D9VK-MiniLand](https://user-images.githubusercontent.com/32371525/65813811-2e743a80-e1da-11e9-9d3a-7c08aec5938d.jpg)

- Cinematics bugs // Cinematics doesn't start with d9vk

With d3d9

![Nostale-D3D9-Cinematics](https://user-images.githubusercontent.com/32371525/65813817-4c419f80-e1da-11e9-9934-de59ba27b8fe.png)

- Framerate

With Windows 10, after 5-10 minutes, the framerate is good ~60-65 fps.

With d9vk, there are a lot of performance drops when there are a lot of components to display or when I turn the camera. Here, there are few players but afternoon, it's not like that.. 


- Freeze // New bug

Sometimes, the game crash and I must restart my PC. (I can't kill the game) // Memory leak?


- APITRACE:

https://1drv.ms/u/s!Armc-fXVwasXg6pMsW1S-o8m2eApOg?e=RvxHrj

**Comment by Joshua-Ashton** [comment]
Characters rendering over the top of each other is depth bias. Need to wait for the extension for that.

wrt. game shop: I don't think this is my bug -- it's rendering a d3d11 window over the top of the d3d9 game based on your screenshot, so there is probably some Wine bug there as to why that isn't working.

**Comment by HoshiYamazaki** [comment]
Hey, so NosTale Gameshop is not rendering since ever (even on OpenGL based wine) and one solution was to install old IE (8, 9 or 10) from Microsoft website but it does not resolve an issue.

From my friend I heard that shop works on steam proton, but I can't make proton to work with old FREETYPE=35 config to get better font scaling, so this is too not way to go.

Another, not releated thing to this thread (I just want to ask), is that NosTale on macOS is not interpreting mouse clicks correctly (bug that was pre wine 1.8), you can't move and I'm curious if moving to VK would fix that (other video event listener? is that an thing? even using MoltenVK wrapper... i'm mostly in webdev/python work now so I don't quite understand). Maybe it's fixed because there were commits to Quartz, but on wine 4.12-4.14 (last I tested) there still was an issue.
Anyway, I gave up on Hackintosh thing for always.

**Comment by HoshiYamazaki** [comment]
Yes, it's working on Steam, since steam redirects http responses into own browser running on steam overlay, so this is one solution to your issue.

If you are interested @jona-1993 - you can get better font rendering using that:
`FREETYPE_PROPERTIES="truetype:interpreter-version=35" wine NostaleClientX.exe EntwellNostaleClient`
But I can't get it to work (it was working on native, not-proton wine year ago), also you can run NosTale directly using `NostaleClientX.exe EntwellNostaleClient` without launcher but you need every update from Gameforge because it will check you on login if you have them or not.

**Comment by jona-1993** [comment]
@HoshiYamazaki If you use the last version of wine, the game shop works with wined3d without IE installation ;)

![Screenshot_20191024_012727](https://user-images.githubusercontent.com/32371525/67441562-a4af6580-f5fd-11e9-84b1-cc3e69eab79f.png)

And thank you for this tips ;)

**Comment by Joshua-Ashton** [comment]
Closed by b738c4220b7f2ea71cf2f1f61521a08606ee7022

**Comment by memegauste** [comment]
@Joshua-Ashton can you tell me why the game can get blackscreen at initial run? I want to help VirtualBox and Parallels developers with that, I think their vGPU miss extension. Feel free to dm me on discord, we talked in the past.
