### ISSUE TITLE
RADV + Skyrim: assertion src/amd/vulkan/radv_meta_copy.c:427: meta_copy_image: Assertion `src_image->info.samples == dest_image->info.samples' failed.

### ISSUE THREAD

**Issue by BNieuwenhuizen** [Joshua-Ashton/d9vk#283]
As in the title, when mesa is compiled with assertions and skyrim (the old one, not SE) is set to 8x msaa (ultra settings)

Got here trying to repro https://github.com/daniel-schuermann/mesa/issues/88

D9VK version is the one provided by proton 4.11 .

The assert indicates a VkCmdCopyImage between images with different sample counts, which goes against spec: "vkCmdCopyImage can be used to copy image data between multisample images, but both images must have the same number of samples."

**Comment by Joshua-Ashton** [comment]
Thanks for the heads up! I will look into this :-)

**Comment by Joshua-Ashton** [comment]
Turns out I was violating the spec/broken in more ways than one here.

The error causing a copy was a typo where I meant to write dst rather than src :frog: !
That was fixed by https://github.com/Joshua-Ashton/d9vk/commit/6a5e8b2ef8cee123a38dfa1a30a1532258b96968 in the [wip-resolvez-fix](https://github.com/Joshua-Ashton/d9vk/tree/wip-resolvez-fix branch) (ignore the buggered indents, will fix that when it reaches master)

However! We still can't use cmdResolveImage, here cause its depth so the plan here is to use ``VK_KHR_depth_stencil_resolve`` for that.
