### ISSUE TITLE
Multiple games missing full resolution list

### ISSUE THREAD

**Issue by DaRkL3AD3R** [Joshua-Ashton/d9vk#341]
Games have a limited list of resolutions available.

### Software information
Call of Duty Modern Warfare 2
Grand Theft Auto 4

### System information
- GPU: 1080 Ti
- Driver: 436.02
- Wine version: N/A
- DXVK version: 0.20 Frog

### Log files
- d3d9.log: http://www.mediafire.com/file/j4pve5zrdvgb7t7/iw4sp_d3d9.log/file

**Comment by Joshua-Ashton** [comment]
Can you show me what you mean?

**Comment by DaRkL3AD3R** [comment]
https://i.imgur.com/e27iAsw.png

The list tops out at 1280x1024 100Hz when in native D3D9 it shows all available resolutions for my display, which is a 2560x1440 144hz panel. The same list of resolutions is in Call of Duty Modern Warfare 2. There may be more games that exhibit this behavior which I haven't found yet.

**Comment by Joshua-Ashton** [comment]
Do you have multiple monitors?

**Comment by DaRkL3AD3R** [comment]
I do and I thought it might be that so I tested with only my primary plugged in. Still the same.

**Comment by DaRkL3AD3R** [comment]
I created api traces for both games but I'm not sure if it is going to help: http://www.mediafire.com/file/h0gqj75c72oyvrj/apitraces.rar/file

Both games still affected as of v 0.30.

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/69688204-4888a700-10bd-11ea-86de-2dbf4f2a4e2e.png)

You have the 4:3 aspect ratio selected.

**Comment by Joshua-Ashton** [comment]
GTA IV's resolution list works fine for me.

Can you make sure this isn't just the fact you had the aspect ratio locked on 4:3?

**Comment by DaRkL3AD3R** [comment]
Still happens regardless of aspect ratio setting. It's more for applying a different scaling to the currently selected resolution and has not bearing on available options. Call of Duty doesn't even have this option anyway.

Strangely enough I just went to test that option and when I launched the game, it decided to use my Nvidia DSR setting of 5120x2880 which is extremely far off the list of available resolutions: https://i.imgur.com/mYnTOXf.png

The second I make an adjustment to the resolution the list crunches down to the normal size and tops out at the old shortened list of 1280x1024 @ 100hz and 5120x2880 is not longer selectable: https://i.imgur.com/ONRtv2k.png

I thought perhaps it might be due to DSR that this issue is happening so I tested with it completely turned off. Same issue is present. All that accomplished was now I can't get 5k out of the game with D9VK anymore.

Just to be clear I am testing this on a native Windows environment as Vulkan provides far better compatibility in modern Windows 10 versions than native DX9 support. You are singlehandedly saving the DX9 library on Windows PCs so I hope this doesn't get tossed aside and ignored.

**Comment by Joshua-Ashton** [comment]
I have a 2060 Super so I will try and see if I can repro there in GTA IV...

**Comment by Joshua-Ashton** [comment]
I can't repro.

**Comment by DaRkL3AD3R** [comment]
I'm wondering if it's maybe your monitor. I have a 2560x1440 144hz monitor. Every resolution gets a 24hz, 60hz, 85hz, 100hz, 120hz and 144hz listing. Under native D3D9 GTA IV and Call of Duty MW2 report the full list of resolutions and refresh rates, but with D9VK it's limited to a significantly smaller range.

What monitor are you testing on out of curiosity? I am thinking it might be 60hz only.

**Comment by Joshua-Ashton** [comment]
Can you try with this build please?

[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3897689/d3d9.zip)

**Comment by DaRkL3AD3R** [comment]
No change.

**Comment by DaRkL3AD3R** [comment]
I have made some progress in understanding this bug. Here I am in game with D9VK able to select all resolutions: https://i.imgur.com/r0AXTxR.png

What I did was go into CRU and stripped away all refresh rates besides 60hz and 144hz. This dramatically cuts down on the reported available resolution/refresh rate combinations that D9VK is reporting to the game, chopping the list down to a much smaller number.

Here's the thing, with D9VK for some odd reason every refresh rate + resolution listing gets multiplied 3 times over. This only happens with D9VK, when using native D3D9 each combination (ie - 2560x1440 @144hz) only gets 1 listing in the resolution switch options.

So this is clearly the problem. D9VK is misreporting each resolution + refresh rate combination when enumerating the list of available options and multiplying each listing times 3. This only happens for COD:MW2 and GTA IV that I have found thus far. Right now my only solution is to basically modify my monitor's EDID in software to lie about what refresh rates it can support to bring the list size down far enough so I can choose either native 2560x1440 144hz or for older games my preferred 5120x2880 144hz DSR.

**Comment by KuraiShidosha** [comment]
Another update to this problem:

I tested another display to see if this problem is due to my monitor or something else, using a basic 640x480 60hz CRT TV through HDMI which only has 2 resolution options and 2 refresh rate options (59hz and 60hz.) The triple listing problem persisted, even with my gaming monitor disconnected. This is not a monitor issue.

I also had a friend test it out on his Nvidia 2080 Ti with a 1080p144hz monitor, and even on Windows he did NOT have this issue. Now I am wondering if this is possibly related to the series graphics card being used as I cannot fathom what else could possibly be variable in this equation that would affect something like this.

Joshua you have a 2060 you do tests for Nvidia on correct? If you have a 10 series card available, would you be able to test on that to see if you can repro this issue? I'm really baffled here on what could be the cause.

**Comment by KuraiShidosha** [comment]
Closing this issue because I was able to reproduce it in a native OpenGL emulator without any connection to D9/DXVK. It's apparently a problem with this specific monitor (perhaps some others?) and OpenGL/Vulkan misreporting non-native resolutions and refresh rate combinations. The issue wasn't present under native D3D9 but when running under Vulkan it presents itself.
