### ISSUE TITLE
Dungeon Siege II → no mouse cursor

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#385]
We should have a mouse cursor, but there is none, so we are stuck on the first menu.

without d9vk:

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #852

### Apitrace file(s)
https://mega.nz/#!Duh3RIRQ!h89Z2ypBY10-yqySNVpi6YPzgzto1f4hD1d9W5LhA3c

### Log files
[steam-39200-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3638624/steam-39200-d3d9.log)
[steam-39200-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3638625/steam-39200-d9vk.log)

**Comment by dlshinobi** [comment]
Go windowed mode, this issue also appears on windows.

**Comment by NerosTie** [comment]
I have a cursor withour d9vk in fullscreen:
![20190921123623_1](https://user-images.githubusercontent.com/4572452/65373449-ffac1080-dc7d-11e9-8876-785b9f256b31.jpg)

**Comment by Crazychicken69** [comment]
Found this video quite helpful: https://youtu.be/WMXsZZCo9S8

**Comment by NerosTie** [comment]
> Found this video quite helpful: https://youtu.be/WMXsZZCo9S8
> Feel free to comment if it didnt work (or if it did)

It is already known the cursor works in windowed mode.

**Comment by Crazychicken69** [comment]
> > Found this video quite helpful: https://youtu.be/WMXsZZCo9S8
> > Feel free to comment if it didnt work (or if it did)
> 
> It is already known the cursor works in windowed mode.

Yip, I know, just seems like it saves time having it in video format ;)

**Comment by Crazychicken69** [comment]
> > > Found this video quite helpful: https://youtu.be/WMXsZZCo9S8
> > > Feel free to comment if it didnt work (or if it did)
> > 
> > 
> > It is already known the cursor works in windowed mode.
> 
> Yip, I know, just seems like it saves time having it in video format ;)

Sorry to see your thumbs down, im new here, i must have selected incorrect profile options, I thought this was here to help people get a solution or some kind of learning space. What is this page though?

**Comment by Crazychicken69** [comment]
Here is the remaining fixes PART 2 of 2
https://youtu.be/wiZntRumPq8

**Comment by NerosTie** [comment]
@Joshua-Ashton can you delete those messages which are not proper fixes but rather ads for a channel on Youtube?

**Comment by Crazychicken69** [comment]
Before I do, its me figuring out a way to show how to resolve the issue in video format to people who like me typed in google and searched the issue i thought i was having alone, i dont like reading all the time and im sure many others feel the same, and i like a challenge, from all the reading doing research, this was my solution that makes the game in a condition that worked for me, i found one video that is similar...saw a Challenge...Took It...but I saw a thumbs up on my video...so...ya...lets see if others want me to keep my posts here. Please Like my video posts above if you here for a similar reason...to find a temporary fix instead of to have a dud game while we wait for some type of update OR perhaps if you prefer video instruction as an easier option to be assisted throughout a fix process...for either...or both...Like my video post...also...dude...you opened this issue on Sep 21, 2019... even if they implement my fix as a update only and include maxwindowsize with transparent borders into it...that id accept as a fix...would you? enough typing for now...can i remove it Sunday night? (People research quite a bit on weekends)

**Comment by CartoonFan** [comment]
Not to be rude, but is the issue still present when using the version at https://github.com/doitsujin/dxvk? That's where d9vk development is these days.

**Comment by Crazychicken69** [comment]
> @Joshua-Ashton can you delete those messages which are not proper fixes but rather ads for a channel on Youtube?

removed. they not ads. they there to help others like me fix a dud game

**Comment by NerosTie** [comment]
@CartoonFan yes, the issue is still present, use `PROTON_USE_WINED3D=1` for now, it's the best way to play the game in good conditions. It also works with `fullscreen=false`, but it's windowed and the videos flicker a lot, I don't know if it's related to DXVK or the windowed mode.

**Comment by CartoonFan** [comment]
Hmm...that's rough. I hope @Joshua-Ashton or @doitsujin are at least aware of the situation. I mean, since everything moved on, the d9vk repo has been basically dead, so I hope they know that some old issues are still present in current dxvk.

**Comment by Blisto91** [comment]
@NerosTie If this is this is still a problem with latest dxvk then please move the issue to that repo. 🙂
Hopefully it can be looked at then.

**Comment by NerosTie** [comment]
Duplicate with https://github.com/doitsujin/dxvk/issues/3020

I close this one.
