### ISSUE TITLE
Windows Compatibility Mode Crash (0xc0000005)

### ISSUE THREAD

**Issue by cynicer** [Joshua-Ashton/d9vk#394]
I'm using the d3d9.dll in a an old game (FHX) on Windows 10, which runs fine (besides the already opened issue #306). The game needs Windows XP compatibility mode set in order to run properly. When I activate it the game won't start and just show this error:

"The application was unable to start correctly (0xc0000005)."
![image](https://user-images.githubusercontent.com/5718282/65406306-6e54af80-dddf-11e9-9e90-f31f57d92563.png)

**There are no logs created.**
### Software information
FHX (Ferentus, Herrcot or Xiones) released in 2004 and closed in 2008.

### System information
- GPU: NVIDIA GTX 1080
- Driver: 430.86
- Wine version: - (latest Windows 10)
- DXVK version: 515643f2c097068ee93faccbeacd59f6dda6d53a

### Apitrace file(s)
None

### Log files
- d3d9.log: -
- d3d11.log: -
- dxgi.log: -

**Comment by qeekeykiki** [comment]
SWTOR also refuse to run in similar way (launcher is ok, client crash immediately and shows same error dialog after pressing play on launcher), though SWTOR doesn't have to be tinkered as far as compatibility mode on Windows.

it's simply:
- if i put d3d9.dll to exe folder => client won't run, crash, and shows same error like above:
"The application was unable to start correctly (0xc0000005)."

(on Linux, such problem never happened. SWTOR works perfectly with D9VK since its early version)

**Comment by Joshua-Ashton** [comment]
Can't fix. Won't fix. Sorry.

**Comment by Joshua-Ashton** [comment]
You may be able to workaround this by using an MSVC build:

[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3644411/d3d9.zip)

**Comment by cynicer** [comment]
MSVC build works for me, thanks!
