### ISSUE TITLE
Rayman Origins (UPlay) black screen

### ISSUE THREAD

**Issue by neuromancer** [Joshua-Ashton/d9vk#78]
Rayman Origins does not render anything (music is fine). You only get a black screen. This game works fine without using d9vk, however it has [major rendering issues later in the game](https://bugs.winehq.org/show_bug.cgi?id=30550) that makes it un-finishable.

### Software information

Rayman Origins (UPlay)

### System information
- GPU: GeForce GTX 1060 6GB:
- Driver: 418.74.0 (Vulkan: 1.1.95)
- Wine version: wine-staging 4.7
- D9VK version: 0.10

### Log files

- [Rayman Origins_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3159492/Rayman.Origins_d3d9.log) 
- Rayman Origins_dxgi.log (it's empty!)

**Comment by Joshua-Ashton** [comment]
Can you retry this on latest master? Fixes a vertex texturing bug.
Builds here: https://git.froggi.es/joshua/d9vk/-/jobs

An APITrace would also be helpful.

**Comment by neuromancer** [comment]
Same issue with a750df75  :(

Log file is here: [Rayman Origins_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3159561/Rayman.Origins_d3d9.log)


I will try to get the apitraces later.

**Comment by cvuchener** [comment]
Although it is not recommended, installing both d3dcompiler_47 and d9vk partially fixes this. The rendering is still not perfect but more sprites are visible than installing d3dcompiler_47 alone.

I tried to make an apitrace but it is too big for me to send.

**Comment by neuromancer** [comment]
I can confirm what @cvuchener said using 6573579e. Since this issue is fixed, let's close this bug. We can re-open one for the missing sprites (although the game looks now playable now).

**Comment by cvuchener** [comment]
I am not sure if this count as a fix. If I understand the warning about d3dcompiler, it replaces some part from d9vk. But I thought it could help to know that the issue may be in those parts replaced by d3dcompiler.

As for the missing sprites it could be an issue with d3dcompiler, not because of d9vk. It does not seem appropriate to open an new issue that happens when I am not following instructions that "cannot be stressed enough".
